[phases.setup]
# Solo incluimos los paquetes que necesitas
nixPkgs = ["php", "composer", "redis", "nodejs"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci",
  "npm run build", # Si usas Laravel Mix o Vite
  "php artisan migrate --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan storage:link"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
